Repository GoogleCloudPlatform/pubsec-declarative-toolkit, pull requests merged in 2023-01, with the labels that each got.

#237 fix: Nomos update
  .github/workflows/guardrails-validation.yaml
  .github/workflows/landing-zone-validation.yaml
Labels: automation, ci

#238 feat: Create codeql.yml
  .github/workflows/codeql.yml
Labels: enhancement, automation, security-controls

#235 feat : Workload project for sandbox landing zone v2
  solutions/project/project-sandbox/Kptfile
  solutions/project/project-sandbox/README.md
  solutions/project/project-sandbox/network/dns.yaml
  solutions/project/project-sandbox/network/nat.yaml
  solutions/project/project-sandbox/network/route.yaml
  solutions/project/project-sandbox/network/subnet.yaml
  solutions/project/project-sandbox/network/vpc.yaml
  solutions/project/project-sandbox/project-iam.yaml
  solutions/project/project-sandbox/project.yaml
  solutions/project/project-sandbox/securitycontrols.md
  solutions/project/project-sandbox/services.yaml
  solutions/project/project-sandbox/setters.yaml
Labels: ssc
