Repository GoogleCloudPlatform/pubsec-declarative-toolkit, pull requests merged in 2023-08, with the labels that each got.

#451 #450 - update setters with DIRECTORY_CUSTOMER_ID instructions
  solutions/core-landing-zone/setters.yaml
Labels: documentation

#443 #296 - day0 install readme must include 2 core-landing-zone pkg instructions link
  README.md
Labels: documentation, developer-experience

#477 added landing zone folder descriptions and diagram
  docs/landing-zone-v2/README.md
  docs/landing-zone-v2/img/folder-structure.png
Labels: documentation

#482 feat: gke-cluster-autopilot package
  solutions/gke/configconnector/gke-cluster-autopilot/Kptfile
  solutions/gke/configconnector/gke-cluster-autopilot/README.md
  solutions/gke/configconnector/gke-cluster-autopilot/application-infrastructure-folder/firewall.yaml
  solutions/gke/configconnector/gke-cluster-autopilot/gke.yaml
  solutions/gke/configconnector/gke-cluster-autopilot/gkehub-featuremembership-acm.yaml
  solutions/gke/configconnector/gke-cluster-autopilot/gkehub-membership.yaml
  solutions/gke/configconnector/gke-cluster-autopilot/host-project/firewall.yaml
  solutions/gke/configconnector/gke-cluster-autopilot/host-project/subnet.yaml
  solutions/gke/configconnector/gke-cluster-autopilot/kms.yaml
  solutions/gke/configconnector/gke-cluster-autopilot/securitycontrols.md
  solutions/gke/configconnector/gke-cluster-autopilot/service-account.yaml
  solutions/gke/configconnector/gke-cluster-autopilot/setters.yaml
Labels: Landing Zone, ssc
